version: "3.8"

services:
  api:
    container_name: web-page-summarizer-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "8080:8080"
    environment:
      QUEUE_URL: ${QUEUE_URL:?err}
      OPENAI_API_KEY: ${OPENAI_API_KEY:?err}
      EXEC_TIMEOUT_SEC: 300
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:?err}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?err}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?err}
      RDB_DSN: ${RDB_DSN:?err}

    volumes:
      - .:/app
    depends_on:
      - localstack

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
