service: web-page-summarizer

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: provided.al2
  stage: dev
  region: ap-northeast-1

  apiGateway:
    apiKeys:
      - ApiKey

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource: "*"
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
        - sqs:GetQueueAttributes
      Resource:
        Fn::GetAtt:
          - taskQueue
          - Arn

  ecr:
    images:
      summaryPageContainerImage:
        path: .
        platform: linux/amd64
        file: ./summarytask/Dockerfile

package:
  individually: true
  include:
    - functions/**
  exclude:
    - ./.bin/**

functions:
  api:
    handler: functions/api/main.go
    package:
      individually: true
      artifact: ./.bin/api.zip
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
            allowCredentials: true
    environment:
      QUEUE_URL: ${ssm:/web-page-summarizer/task/QUEUE_URL}
      RDB_DSN: ${env:RDB_DSN}

  stream-event:
    handler: functions/stream-event/main.go
    package:
      individually: true
      artifact: ./.bin/stream-event.zip
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [summaryTable, StreamArn]
    environment:
      RDB_DSN: ${env:RDB_DSN}

  summary-page:
    image:
      name: summaryPageContainerImage
    description: summary web page
    environment:
      QUEUE_URL: ${ssm:/web-page-summarizer/task/QUEUE_URL}
      OPENAI_API_KEY: ${ssm:/web-page-summarizer/task/OPENAI_API_KEY}
    timeout: 300
    memorySize: 2048
    ephemeralStorageSize: 1024
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - taskQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    summaryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: web_page_summary
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: task_status
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StatusIndex
            KeySchema:
              - AttributeName: task_status
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    taskQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: web_page_summary_queue
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 1800
        Tags:
          - Key: Name
            Value: web_page_summary

    # パラメータストアにKEY・URLを登録
    restApiKey:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /web-page-summarizer/task/API_KEY
        Type: String
        Value: ${env:API_KEY}

    restApiUrl:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /web-page-summarizer/task/API_URL
        Type: String
        Value: ${env:API_URL}
