service: web-page-summarizer

frameworkVersion: "3"

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: ap-northeast-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource: "*"
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
      Resource:
        Fn::GetAtt:
          - taskQueue
          - Arn

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  health:
    handler: bin/health
    events:
      - http:
          path: /health
          method: get
          cors: true
          # private: true

  get-summary:
    handler: bin/get-summary
    events:
      - http:
          path: /get-summary
          method: post
          cors: true
          # private: true
  task:
    handler: bin/task
    events:
      - http:
          path: /task
          method: post
          cors: true
          # private: true
    environment:
      QUEUE_URL: ${ssm:/web-page-summarizer/task/QUEUE_URL}

# you can add CloudFormation resource templates here
resources:
  Resources:
    summaryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: web_page_summary
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    taskQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: web_page_summary_queue
        # ContentBasedDeduplication: Boolean
        # DeduplicationScope: String
        # DelaySeconds: 0
        # FifoQueue: false
        # FifoThroughputLimit: String
        # KmsDataKeyReusePeriodSeconds: Integer
        # KmsMasterKeyId: String
        # MaximumMessageSize: 262144
        # MessageRetentionPeriod: 345600
        ReceiveMessageWaitTimeSeconds: 20
        # RedriveAllowPolicy: Json
        # RedrivePolicy: Json
        # SqsManagedSseEnabled: Boolean
        # VisibilityTimeout: 30
        Tags:
          - Key: Name
            Value: web_page_summary
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
